sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: MwQ/QcZws26phB8rAxRrVjuPdrMy+yqGlOxZLtiIsKYDBWRkqoF+xVVwpCNQ06XGxDhb6PJXf/V54uWNqX3XWaH5oKr2boIH3OI1a6i50aynpvNw4LTK63znFJB6ayFquvvzTSfGv+bJ0O1dh78GRO8S3uW3tOZh8sRsOQO/mEtYmZd61kQiERUMx2H9niaXpz7bMFx581M32VoOv+KTBfzxVF+MTaq6wkfXpaWgCaxK8gXKofxjYwc4TPWvjpy1v5YVKe3hL9jyk5KkjneLxggDJwJEfOWqj3qA9awOSVbwiVTKGgBa4APMgmZzfp9ITWWK0Ows6awdUaXHM7dd3nW1jKYDGpVMiz8P+8DOuSkZg+Q1GOLIX7wzt0Rk0/VDs9OUYmilGHQ1s0EFZXe0EkrfiU7hlKlu2PovCL3yKXOwkZFSdTdVh/kQ7yDxVRG3Y5rGPt0qjnt+Q1QirD+D+0i8GrdvrIPZYFiv/gG6lqHyg+ugPikU5IBTJoXUzsHDT5W8mBKl1QoK27XjIcncYXdct3HOn8bRYHZBtgUcqTVBot3N7gvw+EEZalXYCMFEEuQiwkXGH7VpokOoiDyA+CJg2NtB9kIXu3CKbPUlLoJO4uRn19G9QXrHlFrb8DVlYPbjaYjR9AXcgLugW7TLoM0Y/zkE5uT6Q5K6sKPBD2c=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: D1wCV3iDE1XSV2QFZlxwR3goJhApNOjKGMoGoTr1q6y5ZnGcUUhZclS7mmA9OJtDUZ6KBsuoxPL4BsjRQmlYkuSe3R5a8FpTlHfYsJARoK11wLIv1eWgJUjyaTZJwshMa70gMs0WMXSZGbHdWXpD3K6SaFuPeRsZkt0BFrLfy5hXjp23qPnwAoRxRS2VEnC6BHMqMTtrXyQOto1/19TBhT1aKmuMluqrVhStVT9kkpijeEQl6WwP7GC7wXTBWK4e/LnkQu9yBLyLUqfSUiXt8wUuY/QwTeU/op0oQtjwnxgx4bn8MIGq2kehyGng/Rg6mVvY5z+ACp0oclsKnK8e2o9uc0oS2oB0F16Wm6xd0YNacG0tIpKS6XN5Jznc82e/i5i6xv+sVJ/5RSw0xGgK28i5T2hldYSRQRSkgJE/HFsZJldQA651xaiQPASAhDlOCyC2aaVz5wKbJ9tVeTD4My8HPya6VZ2AbpvHYhRa9IgamZVc9bb2MdwsCkIFK5xzVooTbOzg9Ubz2AhC4qoArVnEfJjYK7LHvS38H/LjDziGqhyHUVpouUtv3ye0BbLByI0Kf6M0wJ7FtZAkaQaubED4Q3AKYaRZUW/11g8MFowHpT/icgkBa1QN5tICBXsrehM59fbVhxeAARCxTTRJs8UsYnahjrvSm9SdTjpaQEo=
